language: java
jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "dfalessicalpoly-github"
    token:
      secure: "b47ccac1905523af22d99a71a06655dd3f99250b"
script:
- ant build
- sonar-scanner